// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimesheetAutomation.Web.Data;

#nullable disable

namespace TimesheetAutomation.Web.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("TimesheetAutomation.Web.Models.DailyTimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualLeaveHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("FinishTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublicHoliday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongServiceLeaveHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("MealBreakMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PublicHolidayHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SickLeaveHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TimeInLieuAccruedHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TimeInLieuTakenHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WorkDate")
                        .IsUnique();

                    b.ToTable("DailyTimeEntries");
                });

            modelBuilder.Entity("TimesheetAutomation.Web.Models.FortnightExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodStartDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FortnightExports");
                });

            modelBuilder.Entity("TimesheetAutomation.Web.Models.TilLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceDailyTimeEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceDailyTimeEntryId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "WorkDate");

                    b.ToTable("TilLedgerEntries");
                });

            modelBuilder.Entity("TimesheetAutomation.Web.Models.TimeEntryAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DailyTimeEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DailyTimeEntryId", "ChangedUtc");

                    b.ToTable("TimeEntryAudits");
                });

            modelBuilder.Entity("TimesheetAutomation.Web.Models.TilLedgerEntry", b =>
                {
                    b.HasOne("TimesheetAutomation.Web.Models.DailyTimeEntry", "SourceDailyTimeEntry")
                        .WithMany("TilLedgerEntries")
                        .HasForeignKey("SourceDailyTimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SourceDailyTimeEntry");
                });

            modelBuilder.Entity("TimesheetAutomation.Web.Models.DailyTimeEntry", b =>
                {
                    b.Navigation("TilLedgerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
